import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.implicitly_wait(20)

shop = driver.find_element_by_css_selector("#menu-item-40 > a")
shop.click()
driver.execute_script("window.scrollBy(0,300);")
item = driver.find_element_by_css_selector(".post-182 > .button")
item.click()
time.sleep(5)
basket = driver.find_element_by_css_selector(".wpmenucart-contents > .cartcontents")
basket.click()
wait = WebDriverWait(driver, 5)
time.sleep(5)
checkout = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cart_totals > div > a")))
#checkout = driver.find_element_by_css_selector(".cart_totals > div > a")
checkout.click()
first_name = driver.find_element_by_id("billing_first_name")
#first_name_check = wait.until(EC.element_located_to_be_selected(first_name))
first_name.send_keys("Ivan")
last_name = driver.find_element_by_id("billing_last_name")
last_name.send_keys("Petrov")
email = driver.find_element_by_id("billing_email")
email.send_keys("petrov@gmail.com")
phone_number = driver.find_element_by_id("billing_phone")
phone_number.send_keys("12345678")
country = driver.find_element_by_css_selector("#s2id_billing_country > a")
country.click()
search = driver.find_element_by_id("s2id_autogen1_search")
search.send_keys("Russia")
select_country = driver.find_element_by_id("select2-results-1")
select_country.click()
address = driver.find_element_by_id("billing_address_1")
address.send_keys("Lenina street")
city = driver.find_element_by_id("billing_city")
city.send_keys("Moscow")
state = driver.find_element_by_id("billing_state")
state.send_keys("Moscow")
postcode = driver.find_element_by_id("billing_postcode")
postcode.send_keys("390000")
order_btn = driver.find_element_by_id("place_order")
order_btn.click()
time.sleep(5)
sign = wait.until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".woocommerce > p"), "Thank you. Your order has been received."))
time.sleep(5)
payment_method = wait.until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".method > strong"), "Direct Bank Transfer"))
driver.quit()
