import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.implicitly_wait(20)

driver.execute_script("window.scrollBy(0,800);")
selenium_ruby = driver.find_element_by_css_selector(".wp-post-image:nth-child(1)")
selenium_ruby.click()
driver.execute_script("window.scrollBy(0,300);")
reviews = driver.find_element_by_css_selector(".reviews_tab > a")
reviews.click()
rating = driver.find_element_by_class_name("star-5")
rating.click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
name = driver.find_element_by_id("author")
name.send_keys("Ivan")
email = driver.find_element_by_id("email")
email.send_keys("ivanov@gmail.com")
submit = driver.find_element_by_id("submit")
submit.click()
